name: build-binary-macos

on:
  workflow_dispatch:

jobs:
  check-upload:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {source: true, binary: true, r: '4.3'}
    uses: ./.github/workflows/build_binary_macos.yml
    with:
      rver: ${{ matrix.config.r}}
      build_source: ${{ matrix.config.source }}
      build_binary: ${{ matrix.config.binary }}
